### ISSUE TITLE
roguereddwarf - _constructURI function allows to break out of json format and to inject malicious properties / code

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-hats-judging#1]
roguereddwarf

high

# _constructURI function allows to break out of json format and to inject malicious properties / code

## Summary
The [Hats._constructURI](https://github.com/Hats-Protocol/hats-protocol/blob/fafcfdf046c0369c1f9e077eacd94a328f9d7af0/src/Hats.sol#L1072-L1138) function is used to construct a URI for a hat from the properties of the hat.

Most of the properties are numbers or addresses.

However the description and image URI of the hat are strings and can be controlled by the admin of the hat.

This means they can be used to break out of the json schema and inject malicious properties.

Also depending on how downstream components handle this data, it can be possible to inject malicious code that can then execute on the victim machine.

## Vulnerability Detail
I show how the `hat.details` field can be used to inject wrong data into the output of `Hats._constructURI`.

Have a look at this test:
```solidity
function testCreateUriCustom() public {
        string memory description = 'for linking","image": "http://www.tophat.com/","properties":{"domain":"1","id":"12345"},"placeholder":"lol';
        uint256 topHatId = hats.mintTopHat(address(this), description, "http://www.tophat.com/");
        string memory jsonUri = hats.uri(topHatId);
        console2.log("encoded URI", jsonUri);
    }
```

It injects malicious `properties` into the json.

The returned base64 data is:
```text/plain
eyJuYW1lIjogIkhhdCIsICJkZXNjcmlwdGlvbiI6ICJmb3IgbGlua2luZyIsImltYWdlIjogImh0dHA6Ly93d3cudG9waGF0LmNvbS8iLCJwcm9wZXJ0aWVzIjp7ImRvbWFpbiI6IjEiLCJpZCI6IjEyMzQ1In0sInBsYWNlaG9sZGVyIjoibG9sIiwgImltYWdlIjogImh0dHA6Ly93d3cudG9waGF0LmNvbS8iLCJwcm9wZXJ0aWVzIjogeyJkb21haW4iOiAiMiIsICJpZCI6ICI1MzkxOTg5MzMzNDMwMTI3OTU4OTMzNDAzMDE3NDAzOTI2MTM0NzI3NDI4ODg0NTA4MTE0NDk2MjIwNzIyMDQ5ODQzMiIsICJwcmV0dHkgaWQiOiAiMHgwMDAwMDAwMjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwic3RhdHVzIjogImFjdGl2ZSIsICJjdXJyZW50IHN1cHBseSI6ICIxIiwgInN1cHBseSBjYXAiOiAiMSIsICJhZG1pbiAoaWQpIjogIjUzOTE5ODkzMzM0MzAxMjc5NTg5MzM0MDMwMTc0MDM5MjYxMzQ3Mjc0Mjg4ODQ1MDgxMTQ0OTYyMjA3MjIwNDk4NDMyIiwgImFkbWluIChwcmV0dHkgaWQpIjogIjB4MDAwMDAwMDIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsICJlbGlnaWJpbGl0eSBtb2R1bGUiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwgInRvZ2dsZSBtb2R1bGUiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwgIm11dGFibGUiOiAiZmFsc2UifX0=
```

It decodes to the following json:
```json
{
   "name":"Hat",
   "description":"for linking",
   "image":"http://www.tophat.com/",
   "properties":{
      "domain":"1",
      "id":"12345"
   },
   "placeholder":"lol",
   "image":"http://www.tophat.com/",
   "properties":{
      "domain":"2",
      "id":"53919893334301279589334030174039261347274288845081144962207220498432",
      "pretty id":"0x0000000200000000000000000000000000000000000000000000000000000000",
      "status":"active",
      "current supply":"1",
      "supply cap":"1",
      "admin (id)":"53919893334301279589334030174039261347274288845081144962207220498432",
      "admin (pretty id)":"0x0000000200000000000000000000000000000000000000000000000000000000",
      "eligibility module":"0x0000000000000000000000000000000000000000",
      "toggle module":"0x0000000000000000000000000000000000000000",
      "mutable":"false"
   }
}
```
It is valid json format and depending on the reader that is used the first malicious occurrence of the `properties` field is used.
This means the downstream components working with this data are using wrong data.

(Note: For simplicity I did not include all fields in my malicious `properties` array. It is trivial to include all fields)

Obviously there are many ways for an attacker to make use of this.

## Impact
An attacker can inject malicious properties / code into the json output of `Hats._constructURI`.

## Code Snippet
https://github.com/Hats-Protocol/hats-protocol/blob/fafcfdf046c0369c1f9e077eacd94a328f9d7af0/src/Hats.sol#L1072-L1138

## Tool used
Manual Review

## Recommendation
The `description` and `image` field contents should be sanitized before using them as json output such that an attacker cannot break out of the field.

**Comment by roguereddwarf** [comment]
Escalate for 10 USDC

I think this issue should be Medium severity. The sponsor confirmed it and said it is valid. He just disagrees with "High" severity.
It is a smart contract security issue since the smart contract can be made to hold dangerous data. E.g. the smart contract should not return that a Hat has some id when it has not.

If it's not possible to check in the smart contract that the strings are safe, the smart contract should not return json.
The json should be generated off-chain. The contract on the other hand might return a struct with all the data which is safe.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I think this issue should be Medium severity. The sponsor confirmed it and said it is valid. He just disagrees with "High" severity.
> It is a smart contract security issue since the smart contract can be made to hold dangerous data. E.g. the smart contract should not return that a Hat has some id when it has not.
> 
> If it's not possible to check in the smart contract that the strings are safe, the smart contract should not return json.
> The json should be generated off-chain. The contract on the other hand might return a struct with all the data which is safe.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid high/medium
Given that this affects only a view function which is just a way to view the hats as pointed out but the Sponsor, 
also the possible impact of this is off-chain. Considering this issue a low severity for the above reasons.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Not a valid high/medium
> Given that this affects only a view function which is just a way to view the hats as pointed out but the Sponsor, 
> also the possible impact of this is off-chain. Considering this issue a low severity for the above reasons.
> 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
