### ISSUE TITLE
GimelSec - `removeSigner()` would fail if `currentSignerCount < validSignerCount`.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-hats-judging#107]
GimelSec

medium

# `removeSigner()` would fail if `currentSignerCount < validSignerCount`.

## Summary

`removeSigner()` would fail if `currentSignerCount < validSignerCount`, nobody could remove invalid signers.

## Vulnerability Detail

Suppose we have a Safe with a signer gate:
* owners.length: 10

At the beginning, only 3 owners wore a valid signer hat (`signerCount` is 3). Then the admin mint 3 hats for other owners (`_countValidSigners(owners)` will be 6), so only 4 owners are invalid.
* currentSignerCount (aka `signerCount`): 3
* validSignerCount (aka `_countValidSigners(owners)`): 6

If users call `removeSigner()` to remove invalid owners, the `signerCount` will update to `newSignerCount = currentSignerCount - 1`, which is `3 - 1 = 2`.
But the 4th call of `removeSigner()` will fail because `currentSignerCount` is underflow in [L390](https://github.com/Hats-Protocol/hats-zodiac/blob/9455cc0957762f5dbbd8e62063d970199109b977/src/HatsSignerGateBase.sol#L390).

The solution is that users should call `reconcileSignerCount()` to update `signerCount` before calling `removeSigner()`. But the solution would result in bad UX, that users don't know they should call `reconcileSignerCount()` first and get confused.

On the other hand, it's possible that `reconcileSignerCount()` may be blocked. See more details in GimelSec issue `reconcileSignerCount() would be blocked if validSignerCount > maxSigners, Safe would not be able to execute any transactions, all assets would be locked`.

Also, `claimSigner()` could call `_swapSigner()` to remove invalid signers, but if `ownerCount < maxSigs`, it will only call `_grantSigner`, those invalid owners are still in the Safe.

## Impact

The `removeSigner()` would fail, nobody could call the function to remove invalid signers.

## Code Snippet

https://github.com/Hats-Protocol/hats-zodiac/blob/9455cc0957762f5dbbd8e62063d970199109b977/src/HatsSignerGateBase.sol#L390

## Tool used

Manual Review

## Recommendation

Use `validSignerCount - 1` in L390:

```solidity
                newSignerCount = validSignerCount - 1;
```

**Comment by zobront** [comment]
Escalate for 10 USDC

While this issue is technically correct, there is no risk. The result is simply bad UX that the user would need to call `reconcileSignerCount()` and re-call the function and it would work as expected.

I imagine there are a large number of Watsons (myself included) who found this issue, spent time trying to figure out if there was any risk associated, and decided not to submit because the worst case scenario was a small hiccup in user experience, not a security risk.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> While this issue is technically correct, there is no risk. The result is simply bad UX that the user would need to call `reconcileSignerCount()` and re-call the function and it would work as expected.
> 
> I imagine there are a large number of Watsons (myself included) who found this issue, spent time trying to figure out if there was any risk associated, and decided not to submit because the worst case scenario was a small hiccup in user experience, not a security risk.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

The issue is a Valid low
Given the impact of the issue is having Bad UX as the user would have to call `reconcileSignerCount` to remove the invalid signer, considering this issue a low severity

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> The issue is a Valid low
> Given the impact of the issue is having Bad UX as the user would have to call `reconcileSignerCount` to remove the invalid signer, considering this issue a low severity

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
