### ISSUE TITLE
GimelSec - An inconsistency in the `MaxSignersReached` of `reconcileSignerCount()` and `claimSigner()`.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-hats-judging#111]
GimelSec

medium

# An inconsistency in the `MaxSignersReached` of `reconcileSignerCount()` and `claimSigner()`.

## Summary

An inconsistency in the `MaxSignersReached` of `reconcileSignerCount()` and `claimSigner()`. Users could call `claimSigner()` to claim as a new signer, but `claimSigner()` should be reverted because the actual signer count exceeds `maxSigners`.

## Vulnerability Detail

The `MaxSignersReached` error in `reconcileSignerCount()` is triggered if `validSignerCount > maxSigners`, but in `claimSigner()` it's triggered by `currentSignerCount >= maxSigs`.

`validSignerCount` is a value obtained dynamically from `_countValidSigners(owners)` which is always the actual current count, but `currentSignerCount` is `signerCount` which may be stale.

Suppose a Safe just attached a signer gate:
* Safe owner: 15
* maxSigners: 10
* validSignerCount (aka `_countValidSigners(owners)`): 12
* signerCount: 0

In `reconcileSignerCount()`, it will trigger `MaxSignersReached` error in [L187](https://github.com/Hats-Protocol/hats-zodiac/blob/9455cc0957762f5dbbd8e62063d970199109b977/src/HatsSignerGateBase.sol#L187-L189) because `12 > 10` is true, but in `claimSigner()` it will not trigger the error in [L40](https://github.com/Hats-Protocol/hats-zodiac/blob/9455cc0957762f5dbbd8e62063d970199109b977/src/HatsSignerGate.sol#L40-L42) because `0 >= 10` is false.

## Impact

Users who wear a signer hat could call `claimSigner()` to claim as a new signer, but `claimSigner()` should be reverted because the actual signer count exceeds `maxSigners`.

## Code Snippet

https://github.com/Hats-Protocol/hats-zodiac/blob/9455cc0957762f5dbbd8e62063d970199109b977/src/HatsSignerGateBase.sol#L187-L189
https://github.com/Hats-Protocol/hats-zodiac/blob/9455cc0957762f5dbbd8e62063d970199109b977/src/HatsSignerGate.sol#L40-L42
https://github.com/Hats-Protocol/hats-zodiac/blob/9455cc0957762f5dbbd8e62063d970199109b977/src/MultiHatsSignerGate.sol#L45-L47

## Tool used

Manual Review

## Recommendation

Do not use the stale `signerCount` variable, always use `getSignerCount()` to dynamically get the current signer count by `_countValidSigners(safe.getOwners())`.

**Comment by zobront** [comment]
Escalate for 10 USDC

This issue is incorrect. While that check will pass, there is another check further down the function that will revert if the `ownerCount` (pulled from current owners on the safe) is greater than or equal to `maxSigs` and there are no invalid owners to replace.

```
address[] memory owners = safe.getOwners();
uint256 ownerCount = owners.length;

if (ownerCount >= maxSigs) {
    bool swapped = _swapSigner(owners, ownerCount, maxSigs, currentSignerCount, msg.sender);
    if (!swapped) {
        // if there are no invalid owners, we can't add a new signer, so we revert
        revert NoInvalidSignersToReplace();
    }
} else {
    _grantSigner(owners, currentSignerCount, msg.sender);
}
```

As a result, there is no possible way that `claimSigner()` can work successfully when we already have the maximum number of valid signers.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This issue is incorrect. While that check will pass, there is another check further down the function that will revert if the `ownerCount` (pulled from current owners on the safe) is greater than or equal to `maxSigs` and there are no invalid owners to replace.
> 
> ```
> address[] memory owners = safe.getOwners();
> uint256 ownerCount = owners.length;
> 
> if (ownerCount >= maxSigs) {
>     bool swapped = _swapSigner(owners, ownerCount, maxSigs, currentSignerCount, msg.sender);
>     if (!swapped) {
>         // if there are no invalid owners, we can't add a new signer, so we revert
>         revert NoInvalidSignersToReplace();
>     }
> } else {
>     _grantSigner(owners, currentSignerCount, msg.sender);
> }
> ```
> 
> As a result, there is no possible way that `claimSigner()` can work successfully when we already have the maximum number of valid signers.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted 

Not a valid issue
As pointed out in the escalation the maxSigs cannot be bypassed by the singer unless there are invalid signers to replace.

**Comment by sherlock-admin** [comment]
> Escalation accepted 
> 
> Not a valid issue
> As pointed out in the escalation the maxSigs cannot be bypassed by the singer unless there are invalid signers to replace. 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
