### ISSUE TITLE
obront - buildHatId returns incorrect value for lowest level child

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-hats-judging#45]
obront

medium

# buildHatId returns incorrect value for lowest level child

## Summary

If we call `buildHatId` with a level 14 hat (ie a hat with a full id that cannot have children) as the admin, rather than reverting (as it should) since they cannot have children, it returns a value.

## Vulnerability Detail

`buildHatId` is a public function that can be used to get the hatId of the child of a given hat. You input the admin hat and the `newHat` and it outputs the new hat's full ID:
```solidity
function buildHatId(uint256 _admin, uint16 _newHat) public pure returns (uint256 id) {
    uint256 mask;
    for (uint256 i = 0; i < MAX_LEVELS;) {
        unchecked {
            mask = uint256(
                type(uint256).max
                // should not overflow given known constants
                >> (TOPHAT_ADDRESS_SPACE + (LOWER_LEVEL_ADDRESS_SPACE * i))
            );
        }
        if (_admin & mask == 0) {
            unchecked {
                id = _admin
                    | (
                        uint256(_newHat)
                        // should not overflow given known constants
                        << (LOWER_LEVEL_ADDRESS_SPACE * (MAX_LEVELS - 1 - i))
                    );
            }
            return id;
        }

        // should not overflow based on < MAX_LEVELS stopping condition
        unchecked {
            ++i;
        }
    }
}
```
In the case that this function is called with an `adminHat` that is already at the lowest possible level, it should revert, since no children are possible. Instead, it returns a specific value:
```solidity
0x00000000.0000.0000.......0000
```

Here is a short test I wrote to illustrate this vulnerability:
```solidity
function testZach__BuildFinalHatId() public {
    uint full = type(uint).max;
    uint child = utils.buildHatId(full, 1);
    assert(child == 0);
}
```

## Impact

The `buildHatId` function returns an incorrect value instead of reverting when it's called with lowest level children. This could mislead users or connecting protocols into thinking a child hat will be produced when, in fact, it will not.

## Code Snippet

https://github.com/Hats-Protocol/hats-protocol/blob/fafcfdf046c0369c1f9e077eacd94a328f9d7af0/src/HatsIdUtilities.sol#L64-L91

## Tool used

Manual Review

## Recommendation

In the event that the no match is found, explicitly revert after the loop.

**Comment by cducrest** [comment]
Escalate for 10 USDC

While true that the utils function will return `0x00...00` when called with an admin hat at the lowest possible level, this is never the case in `Hats.sol` as the protocol took good care to ensure this cannot happen.

`buildHatId()` is called in `getNextId()` in `createHat()`, there is a check on the admin level that prevents such a situation:

```solidity
    function createHat(
        uint256 _admin,
        string calldata _details,
        uint32 _maxSupply,
        address _eligibility,
        address _toggle,
        bool _mutable,
        string calldata _imageURI
    ) public returns (uint256 newHatId) {
        if (uint16(_admin) > 0) {
            revert MaxLevelsReached();
        }

        if (_eligibility == address(0)) revert ZeroAddress();
        if (_toggle == address(0)) revert ZeroAddress();

        newHatId = getNextId(_admin);
```

`buildHatId()` is called in `approveLinkTopHatToTree()`, also protected by a check:

```solidity
    function approveLinkTopHatToTree(uint32 _topHatDomain, uint256 _newAdminHat) external {
        // for everything but the last hat level, check the admin of `_newAdminHat`'s theoretical child hat, since either wearer or admin of `_newAdminHat` can approve
        if (getHatLevel(_newAdminHat) < MAX_LEVELS) {
            _checkAdmin(buildHatId(_newAdminHat, 1));
        }
```

Same in `relinkTopHatWithinTree`:

```solidity
    function relinkTopHatWithinTree(uint32 _topHatDomain, uint256 _newAdminHat) external {
        uint256 fullTopHatId = uint256(_topHatDomain) << 224; // (256 - TOPHAT_ADDRESS_SPACE);

        // msg.sender being capable of both requesting and approving allows us to skip the request step
        _checkAdmin(fullTopHatId); // "requester" must be admin

        // "approver" can be wearer or admin
        if (getHatLevel(_newAdminHat) < MAX_LEVELS) {
            _checkAdmin(buildHatId(_newAdminHat, 1));
        }
```

I think this not a valid medium and rather informative.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> While true that the utils function will return `0x00...00` when called with an admin hat at the lowest possible level, this is never the case in `Hats.sol` as the protocol took good care to ensure this cannot happen.
> 
> `buildHatId()` is called in `getNextId()` in `createHat()`, there is a check on the admin level that prevents such a situation:
> 
> ```solidity
>     function createHat(
>         uint256 _admin,
>         string calldata _details,
>         uint32 _maxSupply,
>         address _eligibility,
>         address _toggle,
>         bool _mutable,
>         string calldata _imageURI
>     ) public returns (uint256 newHatId) {
>         if (uint16(_admin) > 0) {
>             revert MaxLevelsReached();
>         }
> 
>         if (_eligibility == address(0)) revert ZeroAddress();
>         if (_toggle == address(0)) revert ZeroAddress();
> 
>         newHatId = getNextId(_admin);
> ```
> 
> `buildHatId()` is called in `approveLinkTopHatToTree()`, also protected by a check:
> 
> ```solidity
>     function approveLinkTopHatToTree(uint32 _topHatDomain, uint256 _newAdminHat) external {
>         // for everything but the last hat level, check the admin of `_newAdminHat`'s theoretical child hat, since either wearer or admin of `_newAdminHat` can approve
>         if (getHatLevel(_newAdminHat) < MAX_LEVELS) {
>             _checkAdmin(buildHatId(_newAdminHat, 1));
>         }
> ```
> 
> Same in `relinkTopHatWithinTree`:
> 
> ```solidity
>     function relinkTopHatWithinTree(uint32 _topHatDomain, uint256 _newAdminHat) external {
>         uint256 fullTopHatId = uint256(_topHatDomain) << 224; // (256 - TOPHAT_ADDRESS_SPACE);
> 
>         // msg.sender being capable of both requesting and approving allows us to skip the request step
>         _checkAdmin(fullTopHatId); // "requester" must be admin
> 
>         // "approver" can be wearer or admin
>         if (getHatLevel(_newAdminHat) < MAX_LEVELS) {
>             _checkAdmin(buildHatId(_newAdminHat, 1));
>         }
> ```
> 
> I think this not a valid medium and rather informative.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Not a valid high/medium
Given that this is an incorrect value returned in a view function and necessary checks are present wherever it is used, 
considering this issue as a valid low

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Not a valid high/medium
> Given that this is an incorrect value returned in a view funtion and necessary checks are present wherever it is used, 
> considering this issue as a valid low
> 

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
